### ISSUE TITLE
Add Legal Warning

### ISSUE THREAD

**Issue by notr1ch** [kylemcdonald/FreeWifi#1]
Spoofing the MAC of another client over 802.11 is likely illegal in the United States as you would be purposefully interfering with their connection. It may be prudent to add a warning to readme.md that performing the steps described could violate local laws.

> Federal law prohibits the operation, marketing, or sale of any type of jamming equipment, including devices that interfere with cellular and Personal Communication Services (PCS), police radar, Global Positioning Systems (GPS), and wireless networking services (Wi-Fi).

**Comment by qgustavor** [comment]
INAL: seems it's not illegal by itself, but using it in order to commit a crime will make things worse. Well, I only checked non-official sources ([1](https://en.wikipedia.org/wiki/MAC_spoofing), [2](https://www.quora.com/Is-MAC-spoofing-illegal), [3](https://www.reddit.com/r/AskNetsec/comments/2s8v8g/is_changing_mac_address_on_a_wifi_hotspot_illegal/), [4](https://news.ycombinator.com/item?id=5067301)). If it's illegal or not, is illegal bypassing the free WiFi limits?

**Comment by kylemcdonald** [comment]
fixed, thanks!

moreover, if you're doing this on a plane, whose jurisdiction are you under?

**Comment by notr1ch** [comment]
While MAC spoofing itself probably isn't an issue (as noted, mobile OSes do this automatically), I was more concerned over the FCC warning, as intentionally disrupting radio transmissions is most definitely illegal. Spoofing an unused MAC address won't cause issues, but spoofing a currently connected client would basically break the network for both users which when done over Wi-Fi could be classified as intentional interference.

**Comment by pierr3** [comment]
@kylemcdonald On plane, it would depend, but generally on an international flight, you'd be under the jurisdiction of the country where the plane is registered in.
